format:
	uv run ruff format .
	uv run ruff check --fix .

lint:
	uv run ruff check .
	uv run mypy .

run-agent:
	if [ -z "$(model)" ]; then \
		echo "Defaulting to model: gpt-oss:20b"; \
	else \
		echo "Running agent with model: $(model)"; \
	fi
	uv run python -m scripts.agent_cli run_agent --model=$(if $(model),$(model),gpt-oss:20b)

embed-voice-lines:
	uv run python -m scripts.embed_voice_lines \
		--config_path=$(if $(config_path),$(config_path),personas\democracy_officer\config.yaml)

run-discord:
	uv run python -m scripts.discord_bridge run \
		--model=$(if $(model),$(model),qwen3:14b) \
		--mention_only=$(if $(mention_only),$(mention_only),True) \
		--system_prompt_path=$(if $(system_prompt_path),$(system_prompt_path),personas\democracy_officer\helldivers_democracy_officer.txt) \
		--voice_lines_path=$(if $(voice_lines_path),$(voice_lines_path),personas\democracy_officer\voice_lines.txt) \
		--fandom_wiki=$(if $(fandom_wiki),$(fandom_wiki),helldivers) \
		--max_voice_lines=$(if $(max_voice_lines),$(max_voice_lines),13) \
		--context_window=$(if $(context_window),$(context_window),14000) \
		$(if $(allowed_channels),--allowed_channels="$(allowed_channels)",) \
		$(if $(token),--token="$(token)",) \
		$(if $(debug),--debug=$(debug),)

ingest-fandom-wiki:
	uv run python -m scripts.ingest_fandom_lore \
		--model=$(if $(model),$(model),gemma3:4b) \
		--persona_dir=$(if $(persona_dir),$(persona_dir),personas\democracy_officer) \
		--save_dir=$(if $(save_dir),$(save_dir),personas\democracy_officer\debug)