format:
	uv run ruff format .
	uv run ruff check --fix .

lint:
	uv run ruff check .
	uv run mypy .

run-agent:
	if [ -z "$(model)" ]; then \
		echo "Defaulting to model: gpt-oss:20b"; \
	else \
		echo "Running agent with model: $(model)"; \
	fi
	uv run python -m scripts.agent_cli run_agent --model=$(if $(model),$(model),gpt-oss:20b)

run-discord:
	uv run python -m scripts.discord_bridge run \
		--model=$(if $(model),$(model),qwen3:14b) \
		--mention_only=$(if $(mention_only),$(mention_only),True) \
		--system_prompt_path=$(if $(system_prompt_path),$(system_prompt_path),personas\democracy_officer\helldivers_democracy_officer.txt) \
		--voice_lines_path=$(if $(voice_lines_path),$(voice_lines_path),personas\democracy_officer\voice_lines.txt) \
		--fandom_wiki=$(if $(fandom_wiki),$(fandom_wiki),helldivers) \
		$(if $(allowed_channels),--allowed_channels="$(allowed_channels)",) \
		$(if $(token),--token="$(token)",)